git:
  depth: 1
language: c
dist: xenial
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libglu1-mesa-dev
      - mesa-common-dev
      - xorg-dev
      - libasound-dev
script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - gcc --version
  - python --version
  - python fips clean
# build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-release; fi
# run tests
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips set config osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips set config linux-make-release; fi
  - python fips run m6502-nestest
  - python fips run z80-fuse
  - python fips run chips-test

